### ISSUE TITLE
Chat up does not support 1.19.2.

### ISSUE THREAD

**Issue by Kichura** [gnembon/chat-up#17]
When attempting to start up the game using chat up mod installed, the game will just instantly [crash](https://pastebin.com/raw/BhiNU2UQ).

**Comment by duggum** [comment]
I can second this issue.

**Comment by OoLunar** [comment]
I can reproduce this issue

**Comment by JasonHorkles** [comment]
Also applies to 1.19.2

**Comment by zax71** [comment]
I can reproduce this too
