### ISSUE TITLE
Crashes Game on Launch (1.17-pre4)

### ISSUE THREAD

**Issue by duggum** [gnembon/chat-up#9]
Not sure if others are having this issue, but the game crashes upon launch. 

*********************************************************************

Using MultiMC 5 with the following:

- Minecraft: 1.17-pre4
- Fabric: 0.11.3
- Chat Up: chat-up-1.0.0-1.16.jar

Pertinent line from the crash report:

```
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure:
Argument modifier method offsetY(F)F in chatup.mixins.json:ChatHud_chatUpMixin failed injection check, (0/1) succeeded.
Scanned 1 target(s). Using refmap chat-up-refmap.json
```

Full MultiMC crash report is attached.

[chat-up-crash-report.txt](https://github.com/gnembon/chat-up/files/6586697/chat-up-crash-report.txt)

**Comment by Kichura** [comment]
Confirmed since the modding code is still using the java 8 scripts instead of 16.
